# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: 'Fonts | Configure shared font directories.'
  become: yes
  file:
    path: '/usr/local/share/fonts/{{ item.type }}/{{ item.dest | dirname }}'
    state: 'directory'
    group: 'root'
    owner: 'root'
    mode: '0755'
    recurse: yes
  with_items: '{{ fonts_shared }}'
  when: '{{ fonts_shared }}'

- name: 'Fonts | Configure shared fonts.'
  become: yes
  copy:
    src: '{{ item.src }}'
    dest: '/usr/local/share/fonts/{{ item.type }}/{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'fonts_shared_installed'
  with_items: '{{ fonts_shared }}'
  when: '{{ fonts_shared }}'

- name: 'Fonts | Configure user font directories.'
  become: yes
  file:
    path: '/home/{{ item.name }}/.fonts/{{ item.type }}/{{ item.dest | dirname }}'
    state: 'directory'
    owner: '{{ item.owner | default(item.name) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '0755'
    recurse: yes
  with_items: '{{ fonts_user }}'
  when: '{{ fonts_user }}'

- name: 'Fonts | Configure user fonts.'
  become: yes
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ item.name }}/.fonts/{{ item.type }}/{{ item.dest }}'
    owner: '{{ item.owner | default(item.name) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
  register: 'fonts_user_installed'
  with_items: '{{ fonts_user }}'
  when: '{{ fonts_user }}'

- name: 'Font | Rebuild font information.'
  become: yes
  command: 'fc-cache -f -v'
  when: '{{ ansible_os_family == "Debian" and (fonts_multiverse_installed.changed or fonts_microsoft_installed.changed or fonts_shared_installed.changed or fonts_user_installed.changed) }}'